apiVersion: v1
kind: Service
metadata:
  name: my-consumer
spec:
  ports:
    - port: 8081
  selector:
    app: my-consumer
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumer
spec:
  selector:
    matchLabels:
      app: my-consumer
  replicas: 2
  template:
    metadata:
      labels:
        app: my-consumer
    spec:
      containers:
      - args:
        - consumer_run.py
        command:
        - python
        name: my-consumer
        image: vishwithan/dockerhub:my_consumer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: pod-port
          protocol: TCP