apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: wurstmeister/kafka
          name: kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: my_kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper
          ports:
            - containerPort: 9092
              name: kafka