apiVersion: v1
kind: Service
metadata:
  name: my-producer
spec:
  ports:
    - name: www
      nodePort: 32765
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: my-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-producer
spec:
  selector:
    matchLabels:
      app: my-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: my-producer
    spec:
      containers:
      - args:
        - producer_run.py
        command:
        - python
        name: my-producer
        image: vishwithan/dockerhub:my_producer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: pod-port
          protocol: TCP