version: '3'
services:
  message_db:
    image: mysql:8.0
    container_name: message_db
    environment:
      - MYSQL_ROOT_PASSWORD=Mess123
    ports:
      - "3306:3306"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: my_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: my_kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Item1:2:2"
    depends_on:
      - zookeeper
  producer:
    image: my_producer
    ports:
      - "5000:5000"
    container_name: producer_app
    depends_on:
      - kafka
  consumer:
    image: my_consumer
    ports:
      - "8081:8081"
      - "5001:5000"
    container_name: consumer_app
    depends_on:
      - kafka
      - message_db
